
networks:
  gift.net:
    driver: bridge

services:
  app:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - "17550:80"
    volumes :
      - ./gift.appli/:/var/php
      - ./images/img:/var/php/public/img
    working_dir: /var/php/src
    networks:
      - gift.net
    depends_on:
      - sql
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


#############################
# mysql + adminer / can be replaced by mariadb
#############################
  sql:
    image: mariadb:10.6.25
    env_file:
      - .database_env
    ports:
      - "17551:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      gift.net:
        aliases:
          - sql.db

  adminer:
    image: adminer:5.4.2
    ports:
      - "17552:8080"
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
    networks:
      - gift.net
